### PR TITLE
Isolated Documentations from Codebase

### PR DESCRIPTION
**Pull request by cardboardcode**
## What Is This For?

This pull request is to allow for more flexible and, therefore, more user-friendly documentation. While recognizing the grey area in this move to make the documentation separate from the code in how it improves documentation, timely and potentially hefty improvements to documentations need to be made without concerning slowing of EPD clones. 

1. Removed `docs` folder.
2. Created `img` folder to store image files used in root `README.md`.

### CODE REVIEW

**Comment by cardboardcode** [comment]
The Documentations are now hosted on the following repository:

https://github.com/cardboardcode/epd_docs

**Comment by gavanderhoorn** [comment]
Would you want to transfer that repository to this organisation? To keep code + documentation 'close' to each other?

**Comment by cardboardcode** [comment]
@gavanderhoorn 
Would want to. If possible, do let me know how I may do so.

**Comment by gavanderhoorn** [comment]
You are an owner of `ros-industrial`, so you should be able to transfer the repository to this organisation yourself.

**Comment by cardboardcode** [comment]
Noted. Needed to confirm. 

I will take that as a `yes` then on being allowed to transfer the repository myself. 

Will do so by today (14th March 2022).

**Comment by cardboardcode** [comment]
The ownership of repository `epd_docs` has been transferred from `cardboardcode` to `ros-industrial`.

**Pull request merged**
